# Site settings
title: Alex Plagman
author: Alex Plagman
email: alexplagman@gmail.com
description: >-
  Software engineer and hobbyist game developer.
baseurl: ""
url: "https://alexplagman.com"
repo: "https://github.com/APlagman/AlexPlagman.com"
permalink: pretty

twitter_username: alexplagman
github_username:  APlagman
linkedin_username: alexplagman
show_excerpts: true

menu:
  - title: "About"
    url: /about
  - title: "Blog"
    url: /blog

skills:
  - name: "C++"
    level: 80%
    tag: "cpp"
  - name: "C# / ASP.NET"
    level: 80%
    tag: "csharp"
  - name: "Java"
    level: 75%
    tag: "java"
  - name: "HTML / CSS"
    level: 70%
    tag: "web"
  - name: "JavaScript / TypeScript"
    level: 70%
    tag: "js"
  - name: "SQL"
    level: 65%
    tag: "sql"
  - name: "Python"
    level: 50%
    tag: "python"
  - name: "Ruby"
    level: 50%
    tag: "ruby"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-assets

destination: dist
source: src
strict_front_matter: true
incremental: false
collections_dir: collections
collections:
  - posts
  - portfolio

sass:
    style: compressed

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title (Page :num)'
  limit: 0
  sort_field: 'date'
  sort_reverse: true