[en]
  languagename = "English"
  title = "Mori"

  [en.params]
    description = "Mori's personal website"
    keywords = "blog,developer,personal"
    Author = "Mori"
    Email = "hello at morine dot net"
    RssTitle = "Mori's Blog"
    Pronouns1 = "they/she"
    Pronouns2 = "ray/rem"
    PronounsSite = "https://pronouns.within.lgbt/ray/rem/rayr/rayrs/remself"

  [en.menu]
    [[en.menu.main]]
      name = "About"
      weight = 1
      url = "/about/"
    # [[en.menu.main]]
    #   name = "Blog"
    #   weight = 2
    #   url = "/blog/"
    [[en.menu.main]]
      name = "Contact"
      weight = 3
      url = "#contact"
      identifier = "Contact"