[en]
  languagename = "English"
  title = "Marin"

  [en.params]
    info = "Software engineer and hobbyist game developer."
    description = "Marin's personal website"
    keywords = "blog,developer,personal"
    Author = "Marin"
    Email = "hello at natra dot dev"
    RssTitle = "Marin's Blog"

  [en.menu]
    [[en.menu.main]]
      name = "About"
      weight = 1
      url = "/about/"
    # [[en.menu.main]]
    #   name = "Blog"
    #   weight = 2
    #   url = "/blog/"
    [[en.menu.main]]
      name = "Contact"
      weight = 3
      url = "#contact"
      identifier = "Contact"