[en]
  languagename = "English"
  title = "Nat"

  [en.params]
    info = "Software engineer and hobbyist game developer."
    description = "Nat's personal website"
    keywords = "blog,developer,personal"
    Author = "Nat"
    Email = "me at natra dot dev"
    RssTitle = "Nat's Blog"

  [en.menu]
    [[en.menu.main]]
      name = "About"
      weight = 1
      url = "/about/"
    [[en.menu.main]]
      name = "Blog"
      weight = 2
      url = "/blog/"
    [[en.menu.main]]
      name = "Contact"
      weight = 3
      url = "#contact"
      identifier = "Contact"