wordsPerMinute = 220.0
Repo = "https://github.com/natrastellar/website"
favicons = [16, 32, 128]
apple_favicons = [152, 167, 180, 192]

[[social]]
    name = "Github"
    icon = "img/icons.svg"
    id = "github"
    url = "https://github.com/natrastellar/"
    user = "natrastellar"
[[social]]
    name = "Cohost"
    icon = "img/icons.svg"
    id = "cohost"
    url = "https://cohost.org/natrastellar/"
    user = "natrastellar"