#theme = ""

languageCode = "en-us"
defaultContentLanguage = "en"

footnoteReturnLinkContents = "â†©"

enableEmoji = true

summaryLength = 30

paginate = 10
paginatePath = "page"
canonifyUrls = true

favicon_16 = "/favicon.ico"