baseURL = "http://localhost:1313"
title = "Natalie Plagman"
theme = ""
author = "Natalie Plagman"
drafts = true

archetypeDir = "archetypes"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
themesDir = "themes"

languageCode = "en-us"
defaultContentLanguage = "en"

footnoteReturnLinkContents = "â†©"

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"

enableEmoji = true

summaryLength = 30

paginate = 10
paginatePath = "page"
canonifyUrls = true

[languages]
  [languages.en]
    languagename = "English"
    title = "Natalie Plagman"

    [languages.en.params]
      info = "Software engineer and hobbyist game developer."
      description = "Natalie Plagman's personal website"
      keywords = "blog,developer,personal"
      Author = "Natalie Plagman"
      Email = "natplagman at gmail dot com"
      Repo = "https://github.com/natplagman/natplagman.com"
      favicon_16 = "/favicon.ico"

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"
      [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/blog/"

[[params.social]]
  name = "Github"
  icon = "img/icons.svg"
  iconAfter = "#github"
  weight = 1
  url = "https://github.com/natplagman/"
  user = "natplagman"
[[params.social]]
  name = "Linkedin"
  icon = "img/icons.svg"
  iconAfter = "#linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/natplagman/"
  user = "natplagman"
